### ISSUE TITLE
LeagueChunkReader

### ISSUE THREAD

**Issue by Meriipu** [ryancole/LeagueReplayReader#2]
Is the other project -- LeagueChunkReader -- still available?

Not necessarily in a working state but for additional information.

**Comment by toriningen** [comment]
Any update on this issue?

**Comment by ryancole** [comment]
Nah. That project never really materialized. The contents of the old replay files were encrypted and I couldn't figure it out.

**Comment by Mowokuma** [comment]
Sorry to revive this, but I've been working on a rofl parser. it's already kinda usable. If anyone stumble this 'issue',  this is the project: https://github.com/m0w0kuma/ROFL
